(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const MEALS = [['breakfast','朝'],['lunch','昼'],['dinner','夕'],['snack','間食']];
  const ALL_TAGS = ['今日中','近日中','今週の候補','願望','避けたい','在庫切れ'];
  const STORAGE = {
    history:'menuPromptGenerator.v5.history',usuals:'menuPromptGenerator.v5.usuals',drafts:'menuPromptGenerator.v5.drafts',settings:'menuPromptGenerator.v5.settings',pantry:'menuPromptGenerator.v5.pantry'
  };
  const DEFAULT_PROMPT = `以下をもとに、ダイエット相談メモ.txtと常備在庫表.txtを参照し、未定部分と足りていない部分を提案してください。
済のものは変更しないでください。
夕食の主菜は、昨日と重なりすぎないようにしてください。

「今日中」は、今日の献立で使用してください。
「近日中」は数日以内に使いたいものですが、今日一日で使い切ったり、昼と夕の両方へ無理に詰め込んだりしないでください。

「今週の候補」は、現在ある食材の共有用です。今日使う義務や優先度はありません。未定部分に自然に合うものだけ使用し、在庫を減らすこと自体を献立の目的にしないでください。

「願望」は、食べたい気持ちとして可能な範囲で考慮してください。
避けたいもの・在庫切れは使わないでください。

副菜や汁物に少量含まれる肉・魚・卵・豆腐は、主菜一品分のたんぱく質として数えないでください。鍋全体の使用量ではなく、一人分に入る量で判断してください。

最終回答は、朝・昼・夕・間食をそれぞれ1行で書いてください。`;
  const DEFAULT_USUALS = {
    breakfast:['素トースト1枚（5枚切）、ゆで卵1/2個'],
    lunch:['ごはん150g、主菜未定、即席味噌汁（冷凍・救済野菜入り）'],
    dinner:['主菜未定、副菜未定、汁物未定'],
    snack:['無脂肪ギリシャヨーグルト100g','炒り大豆15g']
  };

  function uid(){return globalThis.crypto?.randomUUID?.() || `id-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;}
  const named = (name) => ({id:uid(),name});
  const category = (name,seasoning=false,note='',items=[]) => ({id:uid(),name,seasoning,note,items:items.map(named)});
  const DEFAULT_PANTRY = {categories:[
    category('常備たんぱく質',false,'',['納豆','豆腐150g','卵','鯖水煮缶','ツナ缶（油漬け）','サラダチキン110g','無脂肪ギリシャヨーグルト']),
    category('肉・加工肉',false,'',['豚こま','鶏もも','鶏むね','ひき肉','冷凍唐揚げ','ウインナー','ベーコン','ロースハム','ランチョンミート缶','油揚げ']),
    category('野菜・海藻・缶詰',false,'',['キャベツ','玉ねぎ','にんじん','乾燥わかめ','コーン缶','トマト缶','米ひじき','韓国海苔','きざみのり','きざみねぎ（冷凍）','出汁昆布','塩昆布','鰹節']),
    category('冷凍・救済野菜',false,'市販の冷凍ブロッコリーやほうれん草の場合もある。多くはキャベツの外葉や使い切れなかった野菜を細かく刻んで冷凍したもの。主に昼食で、即席味噌汁やスープへレンジ加熱して加える。種類と量は一定ではなく、家族分の副菜や特定の野菜が必要な料理には勝手に使用しない。',['冷凍・救済野菜（種類不定）']),
    category('主食・麺・粉類',false,'',['米','もちむぎ','食パン5枚切','そうめん','そば','スパゲッティ','マカロニ','ホットケーキミックス','薄力粉','片栗粉','ベーキングパウダー','あえるだけのパスタソース','カレールー（甘口）']),
    category('乳製品・間食材料',false,'',['牛乳','無調整豆乳200ml','スライスチーズ','シュレッドチーズ','粉チーズ','冷凍ブルーベリー','マーガリン','はちみつ','ピーナッツバター','ケーキシロップ','きなこ','すりごま']),
    category('基本調味料',true,'',['醤油','料理酒','みりん風調味料','穀物酢','米油','ごま油','中濃ソース','オリーブオイル','マヨネーズ','ケチャップ','レモン汁','ごまドレッシング','ポン酢','塩','砂糖']),
    category('味噌・だし・スープ類',true,'',['赤味噌','あわせ味噌','すぐとけるみそ（即席味噌汁用）','顆粒だし','めんつゆ','白だし','コンソメ顆粒','コンソメ固形','創味シャンタンDX']),
    category('香味・中華・洋風調味料',true,'',['チューブにんにく','チューブ生姜','オイスターソース','塩麹','粒マスタード','豆板醤']),
    category('香辛料・ハーブ',true,'',['カレー粉','カイエンペッパー粉末','エルブドプロバンス（ミックスハーブ）'])
  ]};

  const clone = (v) => JSON.parse(JSON.stringify(v));
  function load(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):clone(fallback);}catch(e){console.warn(e);return clone(fallback);}}
  const store = (key,value) => localStorage.setItem(key,JSON.stringify(value));
  function normalizeNamed(list){return (Array.isArray(list)?list:[]).map(v=>typeof v==='string'?named(v):{id:v.id||uid(),name:String(v.name||'')}).filter(v=>v.name.trim());}
  function normalizeUsuals(value){const out={};MEALS.forEach(([key])=>out[key]=normalizeNamed(value?.[key]||DEFAULT_USUALS[key]));return out;}
  function normalizePantry(value){const source=Array.isArray(value?.categories)?value.categories:DEFAULT_PANTRY.categories;return{categories:source.map(c=>({id:c.id||uid(),name:String(c.name||'未分類'),seasoning:Boolean(c.seasoning),note:String(c.note||''),items:normalizeNamed(c.items)}))};}
  function blankDraft(){const meals={};MEALS.forEach(([key])=>meals[key]={text:'',status:'未'});return{note:'',meals,urgent:[],candidates:[],wishes:[],avoids:[]};}
  function normalizeTagged(list,allowed,fallback){return (Array.isArray(list)?list:[]).map(v=>typeof v==='string'?{...named(v),tag:fallback}:{id:v.id||uid(),name:String(v.name||''),tag:allowed.includes(v.tag)?v.tag:fallback}).filter(v=>v.name.trim());}
  function normalizeDraft(value){const out=blankDraft();if(!value)return out;out.note=String(value.note||'');MEALS.forEach(([key])=>{const v=value.meals?.[key];if(v)out.meals[key]={text:String(v.text||''),status:v.status==='済'?'済':'未'};});out.urgent=normalizeTagged(value.urgent,['今日中','近日中'],'近日中');out.candidates=normalizeNamed(value.candidates);out.wishes=normalizeNamed(value.wishes);out.avoids=normalizeTagged(value.avoids,['避けたい','在庫切れ'],'避けたい');return out;}
  function normalizeSettings(v){return{appendMode:Boolean(v?.appendMode),promptOn:v?.promptOn!==false,prompt:typeof v?.prompt==='string'&&v.prompt.trim()?v.prompt:DEFAULT_PROMPT,pantryOutput:Boolean(v?.pantryOutput),includeSeasonings:Boolean(v?.includeSeasonings)};}

  let history=load(STORAGE.history,{}), usuals=normalizeUsuals(load(STORAGE.usuals,DEFAULT_USUALS)), drafts=load(STORAGE.drafts,{}), settings=normalizeSettings(load(STORAGE.settings,{})), pantry=normalizePantry(load(STORAGE.pantry,DEFAULT_PANTRY));
  let currentDate=todayKey(), draft=blankDraft(), saveTimer, toastTimer, editingPlan=null, editingUsual=null, editingPantry=null;
  const pad=(n)=>String(n).padStart(2,'0');
  function todayKey(){const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;}
  function addDays(key,n){const [y,m,d]=key.split('-').map(Number),x=new Date(y,m-1,d);x.setDate(x.getDate()+n);return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`;}
  function displayDate(key){const [y,m,d]=key.split('-').map(Number),x=new Date(y,m-1,d);return `${m}月${d}日(${['日','月','火','水','木','金','土'][x.getDay()]})`;}
  const esc=(v)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function toast(msg){const n=$('toast');n.textContent=msg;n.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('show'),1700);}
  const status=(msg)=>$('saveStatus').textContent=msg;

  function draftFromPrevious(key){const prev=normalizeDraft(drafts[addDays(key,-1)]);const out=blankDraft();out.urgent=prev.urgent.filter(v=>v.tag==='近日中').map(v=>({...clone(v),id:uid()}));out.candidates=prev.candidates.map(v=>({...clone(v),id:uid()}));out.wishes=prev.wishes.map(v=>({...clone(v),id:uid()}));out.avoids=prev.avoids.map(v=>({...clone(v),id:uid()}));return out;}
  function readUI(){draft.note=$('dailyNote').value;MEALS.forEach(([key])=>draft.meals[key]={text:$(`${key}Text`).value.trim(),status:$(`${key}Done`).checked?'済':'未'});}
  function saveSettings(){settings={appendMode:$('appendMode').checked,promptOn:$('promptOn').checked,prompt:$('promptText').value,pantryOutput:$('pantryOutput').checked,includeSeasonings:$('includeSeasonings').checked};store(STORAGE.settings,settings);updateSwitches();}
  function saveDraftNow(){readUI();drafts[currentDate]=clone(draft);store(STORAGE.drafts,drafts);saveSettings();status('下書き保存済み');}
  function scheduleSave(){status('保存中…');clearTimeout(saveTimer);saveTimer=setTimeout(()=>{saveDraftNow();generateText();},250);}
  function loadDay(key,saveCurrent=true){if(saveCurrent&&currentDate)saveDraftNow();currentDate=key;$('dateInput').value=key;$('dateDisplay').textContent=displayDate(key);if(drafts[key])draft=normalizeDraft(drafts[key]);else{draft=draftFromPrevious(key);drafts[key]=clone(draft);store(STORAGE.drafts,drafts);}writeUI();renderAll();status('読み込み済み');}
  function writeUI(){$('dailyNote').value=draft.note;MEALS.forEach(([key])=>{$(`${key}Text`).value=draft.meals[key].text;$(`${key}Done`).checked=draft.meals[key].status==='済';});updateSwitches();}
  function updateSwitches(){$('appendModeText').textContent=$('appendMode').checked?'追記':'上書き';$('promptState').textContent=$('promptOn').checked?'ON':'OFF';MEALS.forEach(([key])=>$(`${key}State`).textContent=$(`${key}Done`).checked?'済':'未');}

  function renderMeals(){const root=$('meals');root.innerHTML='';MEALS.forEach(([key,label])=>{const card=document.createElement('div');card.className='meal-card';card.innerHTML=`<div class="title">${label}</div><div class="meal-grid"><div><label for="${key}Text">${label}の予定・食べたもの</label><textarea id="${key}Text"></textarea></div><div><label>状態</label><label class="switch"><input id="${key}Done" type="checkbox"><span class="track"></span><span id="${key}State">未</span></label></div></div><div class="buttons"><button class="small" data-yesterday-meal="${key}">昨日と同じ</button><button class="small" data-undecided="${key}">未定</button><button class="small" data-clear-meal="${key}">クリア</button><button class="small" data-register-usual="${key}">今の内容をいつものに登録</button></div><div id="${key}Chips" class="chips"></div>`;root.appendChild(card);});
    MEALS.forEach(([key])=>{$(`${key}Text`).addEventListener('input',scheduleSave);$(`${key}Done`).addEventListener('change',()=>{updateSwitches();scheduleSave();});});
    root.querySelectorAll('[data-yesterday-meal]').forEach(b=>b.onclick=()=>copyYesterdayMeal(b.dataset.yesterdayMeal));root.querySelectorAll('[data-undecided]').forEach(b=>b.onclick=()=>{$(`${b.dataset.undecided}Text`).value='未定';$(`${b.dataset.undecided}Done`).checked=false;updateSwitches();saveDraftNow();generateText();});root.querySelectorAll('[data-clear-meal]').forEach(b=>b.onclick=()=>{$(`${b.dataset.clearMeal}Text`).value='';$(`${b.dataset.clearMeal}Done`).checked=false;updateSwitches();saveDraftNow();generateText();});root.querySelectorAll('[data-register-usual]').forEach(b=>b.onclick=()=>registerUsual(b.dataset.registerUsual));renderUsualChips();}
  function renderUsualChips(){MEALS.forEach(([key])=>{const root=$(`${key}Chips`);if(!root)return;root.innerHTML='';usuals[key].forEach(v=>{const b=document.createElement('button');b.className='chip';b.textContent=v.name;b.onclick=()=>{const field=$(`${key}Text`);field.value=settings.appendMode&&field.value.trim()?`${field.value.trim()}、${v.name}`:v.name;scheduleSave();};root.appendChild(b);});});}
  function yesterdayMeals(){return history[addDays(currentDate,-1)]?.meals||{};}
  function copyYesterdayMeal(key){const v=yesterdayMeals()[key];if(!v)return toast('昨日の保存がない');$(`${key}Text`).value=v;$(`${key}Done`).checked=false;updateSwitches();saveDraftNow();generateText();}
  function sameAllMeals(){const m=yesterdayMeals();let used=false;MEALS.forEach(([key])=>{if(m[key]){$(`${key}Text`).value=m[key];$(`${key}Done`).checked=false;used=true;}});if(!used)return toast('昨日の保存がない');updateSwitches();saveDraftNow();generateText();toast('昨日と同じにした');}
  function registerUsual(key){const name=$(`${key}Text`).value.trim();if(!name)return toast('内容を入力して');usuals[key].push(named(name));store(STORAGE.usuals,usuals);renderUsualChips();renderUsualEditor();toast('いつものに登録した');}

  const groupForTag=(tag)=>tag==='今日中'||tag==='近日中'?'urgent':tag==='今週の候補'?'candidates':tag==='願望'?'wishes':'avoids';
  function entries(){return [...draft.urgent.map(v=>({...v,group:'urgent'})),...draft.candidates.map(v=>({...v,tag:'今週の候補',group:'candidates'})),...draft.wishes.map(v=>({...v,tag:'願望',group:'wishes'})),...draft.avoids.map(v=>({...v,group:'avoids'}))];}
  function addPlan(group,name,tag){name=String(name||'').trim();if(!name)return toast('品名を入力して');const v={id:uid(),name};if(group==='urgent'||group==='avoids')v.tag=tag;draft[group].push(v);saveDraftNow();renderPlans();generateText();}
  function deletePlan(group,id){draft[group]=draft[group].filter(v=>v.id!==id);if(editingPlan?.id===id)editingPlan=null;saveDraftNow();renderPlans();generateText();}
  function savePlanEdit(oldGroup,id,name,tag){name=name.trim();if(!name)return toast('空欄では保存できない');const old=draft[oldGroup].find(v=>v.id===id);if(!old)return;draft[oldGroup]=draft[oldGroup].filter(v=>v.id!==id);const newGroup=groupForTag(tag),v={id,name};if(newGroup==='urgent'||newGroup==='avoids')v.tag=tag;draft[newGroup].push(v);editingPlan=null;saveDraftNow();renderPlans();generateText();}
  function renderPlanList(rootId,filter){const root=$(rootId),list=entries().filter(filter);if(!list.length){root.innerHTML='<div class="empty">未登録</div>';return;}root.innerHTML=list.map(v=>{if(editingPlan?.id===v.id)return `<div class="item"><div class="edit-grid"><input data-plan-edit-name value="${esc(v.name)}"><select data-plan-edit-tag>${ALL_TAGS.map(t=>`<option${t===v.tag?' selected':''}>${t}</option>`).join('')}</select><div class="item-actions"><button class="small primary" data-plan-save="${v.id}" data-old-group="${v.group}">保存</button><button class="small" data-plan-cancel>キャンセル</button></div></div></div>`;return `<div class="item"><div>${esc(v.name)}<span class="tag">${esc(v.tag)}</span></div><div class="item-actions"><button class="small" data-plan-edit="${v.id}" data-plan-group="${v.group}">編集</button><button class="small danger" data-plan-delete="${v.id}" data-plan-group="${v.group}">削除</button></div></div>`;}).join('');
    root.querySelectorAll('[data-plan-edit]').forEach(b=>b.onclick=()=>{editingPlan={id:b.dataset.planEdit,group:b.dataset.planGroup};renderPlans();});root.querySelectorAll('[data-plan-delete]').forEach(b=>b.onclick=()=>deletePlan(b.dataset.planGroup,b.dataset.planDelete));root.querySelectorAll('[data-plan-save]').forEach(b=>b.onclick=()=>savePlanEdit(b.dataset.oldGroup,b.dataset.planSave,root.querySelector('[data-plan-edit-name]').value,root.querySelector('[data-plan-edit-tag]').value));root.querySelectorAll('[data-plan-cancel]').forEach(b=>b.onclick=()=>{editingPlan=null;renderPlans();});}
  function renderPlans(){renderPlanList('urgentList',v=>v.group==='urgent');renderPlanList('candidateList',v=>v.group==='candidates');renderPlanList('wishList',v=>v.group==='wishes');renderPlanList('avoidList',v=>v.group==='avoids');}

  function renderUsualEditor(){const root=$('usualEditor');root.innerHTML=MEALS.map(([key,label])=>`<div><h3>${label}</h3><div id="usual-${key}"></div><div class="row"><input id="usual-add-${key}" placeholder="${label}の定番"><button class="primary small" data-usual-add="${key}">登録</button></div></div>`).join('');MEALS.forEach(([key])=>{const list=$(`usual-${key}`);list.innerHTML=usuals[key].length?usuals[key].map(v=>editingUsual?.id===v.id?`<div class="item"><div class="edit-grid"><input data-usual-edit-name value="${esc(v.name)}"><div></div><div class="item-actions"><button class="small primary" data-usual-save="${v.id}" data-usual-key="${key}">保存</button><button class="small" data-usual-cancel>キャンセル</button></div></div></div>`:`<div class="item"><div>${esc(v.name)}</div><div class="item-actions"><button class="small" data-usual-edit="${v.id}" data-usual-key="${key}">編集</button><button class="small danger" data-usual-delete="${v.id}" data-usual-key="${key}">削除</button></div></div>`).join(''):'<div class="empty">未登録</div>';});
    root.querySelectorAll('[data-usual-add]').forEach(b=>b.onclick=()=>{const key=b.dataset.usualAdd,n=$(`usual-add-${key}`).value.trim();if(!n)return toast('内容を入力して');usuals[key].push(named(n));store(STORAGE.usuals,usuals);renderUsualEditor();renderUsualChips();});root.querySelectorAll('[data-usual-edit]').forEach(b=>b.onclick=()=>{editingUsual={id:b.dataset.usualEdit,key:b.dataset.usualKey};renderUsualEditor();});root.querySelectorAll('[data-usual-delete]').forEach(b=>b.onclick=()=>{const key=b.dataset.usualKey;usuals[key]=usuals[key].filter(v=>v.id!==b.dataset.usualDelete);store(STORAGE.usuals,usuals);renderUsualEditor();renderUsualChips();});root.querySelectorAll('[data-usual-save]').forEach(b=>b.onclick=()=>{const n=root.querySelector('[data-usual-edit-name]').value.trim();if(!n)return toast('空欄では保存できない');const v=usuals[b.dataset.usualKey].find(x=>x.id===b.dataset.usualSave);if(v)v.name=n;editingUsual=null;store(STORAGE.usuals,usuals);renderUsualEditor();renderUsualChips();});root.querySelectorAll('[data-usual-cancel]').forEach(b=>b.onclick=()=>{editingUsual=null;renderUsualEditor();});}

  function renderPantry(){const root=$('pantryEditor');root.innerHTML=pantry.categories.map(c=>`<details class="pantry-category"><summary>${esc(c.name)}${c.seasoning?' <span class="tag">調味料</span>':''}</summary><div class="pantry-note">${esc(c.note)}</div><div class="buttons"><button class="small" data-cat-rename="${c.id}">分類名編集</button><button class="small" data-cat-note="${c.id}">説明編集</button><button class="small danger" data-cat-delete="${c.id}">分類削除</button></div><div>${c.items.length?c.items.map(v=>editingPantry?.id===v.id?`<div class="item"><div class="edit-grid"><input data-pantry-edit-name value="${esc(v.name)}"><div></div><div class="item-actions"><button class="small primary" data-pantry-save="${v.id}" data-cat-id="${c.id}">保存</button><button class="small" data-pantry-cancel>キャンセル</button></div></div></div>`:`<div class="item"><div>${esc(v.name)}</div><div class="item-actions"><button class="small" data-pantry-edit="${v.id}" data-cat-id="${c.id}">編集</button><button class="small danger" data-pantry-delete="${v.id}" data-cat-id="${c.id}">削除</button></div></div>`).join(''):'<div class="empty">未登録</div>'}</div><div class="row"><input id="pantry-add-${c.id}" placeholder="在庫品名"><button class="small primary" data-pantry-add="${c.id}">追加</button></div></details>`).join('');
    root.querySelectorAll('[data-pantry-add]').forEach(b=>b.onclick=()=>{const c=pantry.categories.find(x=>x.id===b.dataset.pantryAdd),n=$(`pantry-add-${c.id}`).value.trim();if(!n)return toast('品名を入力して');c.items.push(named(n));store(STORAGE.pantry,pantry);renderPantry();generateText();});root.querySelectorAll('[data-pantry-edit]').forEach(b=>b.onclick=()=>{editingPantry={id:b.dataset.pantryEdit,catId:b.dataset.catId};renderPantry();});root.querySelectorAll('[data-pantry-delete]').forEach(b=>b.onclick=()=>{const c=pantry.categories.find(x=>x.id===b.dataset.catId);c.items=c.items.filter(v=>v.id!==b.dataset.pantryDelete);store(STORAGE.pantry,pantry);renderPantry();generateText();});root.querySelectorAll('[data-pantry-save]').forEach(b=>b.onclick=()=>{const n=root.querySelector('[data-pantry-edit-name]').value.trim();if(!n)return toast('空欄では保存できない');const c=pantry.categories.find(x=>x.id===b.dataset.catId),v=c.items.find(x=>x.id===b.dataset.pantrySave);if(v)v.name=n;editingPantry=null;store(STORAGE.pantry,pantry);renderPantry();generateText();});root.querySelectorAll('[data-pantry-cancel]').forEach(b=>b.onclick=()=>{editingPantry=null;renderPantry();});root.querySelectorAll('[data-cat-rename]').forEach(b=>b.onclick=()=>{const c=pantry.categories.find(x=>x.id===b.dataset.catRename),n=prompt('分類名',c.name);if(n?.trim()){c.name=n.trim();store(STORAGE.pantry,pantry);renderPantry();generateText();}});root.querySelectorAll('[data-cat-note]').forEach(b=>b.onclick=()=>{const c=pantry.categories.find(x=>x.id===b.dataset.catNote),n=prompt('説明',c.note);if(n!==null){c.note=n;store(STORAGE.pantry,pantry);renderPantry();generateText();}});root.querySelectorAll('[data-cat-delete]').forEach(b=>b.onclick=()=>{const c=pantry.categories.find(x=>x.id===b.dataset.catDelete);if(!confirm(`「${c.name}」を削除する？`))return;pantry.categories=pantry.categories.filter(x=>x.id!==c.id);store(STORAGE.pantry,pantry);renderPantry();generateText();});}

  const cleanMeal=(v)=>String(v||'').replace(/[（(]\s*(済|未)\s*[）)]/g,'').trim();
  function mealLines(meals,statusOn){return MEALS.map(([key,label])=>{const v=meals?.[key];if(v&&typeof v==='object')return `${label}:${cleanMeal(v.text)||'未定'}${statusOn?`(${v.status})`:''}`;return `${label}:${cleanMeal(v)||'未定'}`;}).join('\n');}
  const names=(list)=>list.length?list.map(v=>v.name).join('、'):'なし';
  function urgentLines(){const a=draft.urgent.filter(v=>v.tag==='今日中'),b=draft.urgent.filter(v=>v.tag==='近日中');return `今日中：${names(a)}\n近日中：${names(b)}`;}
  function avoidLines(){const a=draft.avoids.filter(v=>v.tag==='避けたい'),b=draft.avoids.filter(v=>v.tag==='在庫切れ');return `避けたい：${names(a)}\n在庫切れ：${names(b)}`;}
  function pantryText(){return pantry.categories.filter(c=>settings.includeSeasonings||!c.seasoning).map(c=>`［${c.name}］\n${names(c.items)}${c.note?`\n注：${c.note}`:''}`).join('\n\n')||'なし';}
  function historyText(key){const r=history[key];return r?mealLines(r.meals,false):'保存なし';}
  function generateText(){readUI();saveSettings();const p=[displayDate(currentDate)];if(settings.promptOn&&settings.prompt.trim())p.push(settings.prompt.trim());p.push(`【今日の補足・相談したいこと】\n${draft.note.trim()||'なし'}`);p.push(`【今日食べるもの】\n${mealLines(draft.meals,true)}`);p.push(`【使い切りを優先したいもの】\n${urgentLines()}`);p.push(`【今週の候補】\n${names(draft.candidates)}`);p.push(`【食べたいもの】\n願望：${names(draft.wishes)}`);p.push(`【避けたいもの・在庫切れ】\n${avoidLines()}`);p.push(`【昨日食べたもの】\n${historyText(addDays(currentDate,-1))}`);if(settings.pantryOutput)p.push(`【常備在庫表】\n${pantryText()}`);$('outputText').value=p.join('\n\n');return $('outputText').value;}
  function parseFinalMenu(raw){const text=String(raw||'').replace(/\r\n/g,'\n'),aliases={breakfast:['朝','朝食','あさ','朝ごはん','朝ご飯'],lunch:['昼','昼食','ひる','昼ごはん','昼ご飯','ランチ'],dinner:['夕','夕食','夜','夜食','晩','晩ごはん','晩ご飯','夕ごはん','夕ご飯','夜ごはん','夜ご飯','ディナー'],snack:['間食','おやつ','お菓子','補食','デザート']},out={};Object.entries(aliases).forEach(([key,arr])=>{const ns=arr.map(v=>v.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),m=text.match(new RegExp(`(?:^|\\n)\\s*(?:${ns})\\s*[:：]\\s*([^\\n]+)`,'m'));if(m)out[key]=cleanMeal(m[1]);});return out;}
  function saveRecord(key,raw){const parsed=parseFinalMenu(raw);if(!Object.keys(parsed).length){toast('朝・昼・夕・間食の行が見つからない');return false;}if(key===currentDate)saveDraftNow();const base=drafts[key]?normalizeDraft(drafts[key]):blankDraft(),meals={};MEALS.forEach(([k])=>meals[k]=parsed[k]||'');history[key]={date:key,meals,rawText:String(raw||'').trim(),urgent:clone(base.urgent),candidates:clone(base.candidates),wishes:clone(base.wishes),avoids:clone(base.avoids),savedAt:new Date().toISOString()};store(STORAGE.history,history);renderYesterday();renderHistory();generateText();return true;}
  function renderYesterday(){const key=addDays(currentDate,-1);$('yesterdayBox').textContent=`${displayDate(key)}\n${historyText(key)}`;}
  function renderHistory(){const root=$('historyList'),keys=Object.keys(history).sort().reverse();root.innerHTML=keys.length?keys.slice(0,30).map(key=>`<div class="history-entry"><b>${displayDate(key)}</b><div class="history-summary">${esc(historyText(key))}</div><div class="buttons"><button class="small" data-history-view="${key}">表示</button><button class="small danger" data-history-delete="${key}">削除</button></div></div>`).join(''):'<div class="empty">保存履歴なし</div>';root.querySelectorAll('[data-history-view]').forEach(b=>b.onclick=()=>{$('finalMenu').value=history[b.dataset.historyView].rawText||historyText(b.dataset.historyView);});root.querySelectorAll('[data-history-delete]').forEach(b=>b.onclick=()=>{if(!confirm(`${displayDate(b.dataset.historyDelete)}の履歴を削除する？`))return;delete history[b.dataset.historyDelete];store(STORAGE.history,history);renderHistory();renderYesterday();generateText();});updateMonths();}

  function monthKeys(){return[...new Set([...Object.keys(history),...Object.keys(drafts)].filter(k=>/^\d{4}-\d{2}-\d{2}$/.test(k)).map(k=>k.slice(0,7)))].sort().reverse();}
  function updateMonths(){const s=$('monthSelect'),old=s.value,ms=monthKeys();s.innerHTML=ms.map(m=>`<option value="${m}">${m.slice(0,4)}年${Number(m.slice(5))}月</option>`).join('');if(ms.includes(old))s.value=old;}
  function subset(obj,month){const out={};Object.entries(obj).forEach(([k,v])=>{if(k.startsWith(`${month}-`))out[k]=v;});return out;}
  function exportJson(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function importJson(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!confirm('現在のv5データへ読み込み内容を統合する？'))return;history={...history,...(data.history||{})};drafts={...drafts,...(data.drafts||{})};if(data.usuals)usuals=normalizeUsuals(data.usuals);if(data.settings)settings=normalizeSettings(data.settings);if(data.pantry)pantry=normalizePantry(data.pantry);store(STORAGE.history,history);store(STORAGE.drafts,drafts);store(STORAGE.usuals,usuals);store(STORAGE.settings,settings);store(STORAGE.pantry,pantry);applySettings();renderUsualEditor();renderPantry();loadDay(currentDate,false);toast('JSONを読み込んだ');}catch(e){console.error(e);toast('JSONを読み込めなかった');}};r.readAsText(file);}
  async function copyOutput(){const text=generateText();try{await navigator.clipboard.writeText(text);toast('コピーした');}catch{$('outputText').focus();$('outputText').select();document.execCommand('copy');toast('コピーした');}}
  function applySettings(){$('appendMode').checked=settings.appendMode;$('promptOn').checked=settings.promptOn;$('promptText').value=settings.prompt;$('pantryOutput').checked=settings.pantryOutput;$('includeSeasonings').checked=settings.includeSeasonings;updateSwitches();}
  function renderAll(){renderPlans();renderYesterday();renderHistory();renderUsualChips();generateText();}

  function bind(){
    $('prevDay').onclick=()=>loadDay(addDays(currentDate,-1));$('nextDay').onclick=()=>loadDay(addDays(currentDate,1));$('todayBtn').onclick=()=>loadDay(todayKey());$('dateInput').onchange=()=>$('dateInput').value&&loadDay($('dateInput').value);$('dailyNote').oninput=scheduleSave;$('appendMode').onchange=()=>{saveSettings();};$('sameAllMeals').onclick=sameAllMeals;
    $('addUrgent').onclick=()=>{addPlan('urgent',$('urgentName').value,$('urgentTag').value);$('urgentName').value='';};$('addCandidate').onclick=()=>{addPlan('candidates',$('candidateName').value);$('candidateName').value='';};$('addWish').onclick=()=>{addPlan('wishes',$('wishName').value);$('wishName').value='';};$('addAvoid').onclick=()=>{addPlan('avoids',$('avoidName').value,$('avoidTag').value);$('avoidName').value='';};
    ['promptOn','promptText','pantryOutput','includeSeasonings'].forEach(id=>$(id).addEventListener(id==='promptText'?'input':'change',()=>{saveSettings();generateText();}));$('resetPrompt').onclick=()=>{$('promptText').value=DEFAULT_PROMPT;saveSettings();generateText();toast('標準へ戻した');};$('generateText').onclick=()=>{generateText();toast('相談文を更新した');};$('copyText').onclick=copyOutput;$('selectText').onclick=()=>{$('outputText').focus();$('outputText').select();};
    $('pasteFinal').onclick=async()=>{try{$('finalMenu').value=await navigator.clipboard.readText();}catch{toast('貼り付け権限がないので手動で貼ってね');}};$('useOutput').onclick=()=>{$('finalMenu').value=generateText();};$('saveToday').onclick=()=>saveRecord(currentDate,$('finalMenu').value)&&toast('今日として保存した');$('saveYesterday').onclick=()=>saveRecord(addDays(currentDate,-1),$('yesterdayEdit').value)&&toast('昨日として保存した');$('loadYesterdayToEdit').onclick=()=>{const k=addDays(currentDate,-1);$('yesterdayEdit').value=history[k]?.rawText||historyText(k);};$('reloadYesterday').onclick=renderYesterday;
    $('addCategory').onclick=()=>{const n=$('newCategoryName').value.trim();if(!n)return toast('分類名を入力して');pantry.categories.push(category(n,$('newCategorySeasoning').checked));$('newCategoryName').value='';$('newCategorySeasoning').checked=false;store(STORAGE.pantry,pantry);renderPantry();generateText();};
    $('exportAll').onclick=()=>exportJson({version:'5.0.2',exportedAt:new Date().toISOString(),history,drafts,usuals,settings,pantry},`menu-prompt-backup-${todayKey()}.json`);$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=()=>{const f=$('importFile').files?.[0];if(f)importJson(f);$('importFile').value='';};$('exportMonth').onclick=()=>{const m=$('monthSelect').value;if(!m)return toast('月の記録がない');exportJson({version:'5.0.2',type:'month',month:m,exportedAt:new Date().toISOString(),history:subset(history,m),drafts:subset(drafts,m)},`menu-prompt-${m}.json`);};$('deleteMonth').onclick=()=>{const m=$('monthSelect').value;if(!m)return toast('月の記録がない');if(!confirm(`${m.slice(0,4)}年${Number(m.slice(5))}月の履歴と下書きを削除する？`))return;Object.keys(history).forEach(k=>k.startsWith(`${m}-`)&&delete history[k]);Object.keys(drafts).forEach(k=>k.startsWith(`${m}-`)&&delete drafts[k]);store(STORAGE.history,history);store(STORAGE.drafts,drafts);loadDay(currentDate,false);toast('月別データを削除した');};
  }
  function init(){renderMeals();applySettings();bind();renderUsualEditor();renderPantry();loadDay(currentDate,false);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);window.addEventListener('beforeunload',saveDraftNow);window.addEventListener('scroll',()=>{if(window.scrollX)window.scrollTo(0,window.scrollY);},{passive:true});}
  init();
})();
